practice/hello/urls.py
from unicodedata import name
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("<str:name>", views.greet, name="greet"),
    path("mike", views.mike, name="mike"),
    path("marvhiee", views.marvhiee, name="marvhiee")
]

practice/practice/urls.py
from xml.etree.ElementInclude import include
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', include("hello.urls")),
    path('task/', include("task.urls")),
    path('newyear/', include("newyear.urls"))
]

practice/task/urls.py
from django.urls import path

from . import views

app_name = "task"
urlpatterns = [
    path("", views.index, name="index"),
    path("add", views.add, name="add")
]

practice/hello/views.py
from django.http import HttpRequest, HttpResponse
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, "hello/index.html")

def mike(request):
    return HttpResponse("Hello, Mike!")

def marvhiee(request):
    return HttpResponse("Hello, Marvhiee!")

def greet(request, name):
    return render(request, "hello/greet.html", {
        "name": name.capitalize()
    })

practice/newyear/views.py
import datetime

from django.shortcuts import render

# Create your views here.
def index(request):
    now = datetime.datetime.now()
    return render(request, "newyear/index.html", {
        "newyear": now.month == 1 and now.day == 1
    })

practice/task/views.py
from django import forms
from django.shortcuts import render

task = ["foo", "bar", "baz"]

class NewTaskForm(forms.Form):
    tasks = forms.CharField(label="New Task")
    priority = forms.IntegerField(label="Priority", min_value=1, max_value=10)

# Create your views here.
def index(request):
    return render(request, "task/index.html", {
        "task": task
    })

def add(request):
    if request.method == "POST":
        form = NewTaskForm(request.POST)
        if form.is_valid():
            task = form.cleaned_data["task"]
            tasks.append(task)
        else:
            return render(request, "task/add.html", {
                "form": form
            })
    return render(request, "task/add.html", {
        "form":NewTaskForm()
    })

practice/hello/templates/hello/greet.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Hello, {{ name }}!</h1>
</body>
</html>

practice/hello/templates/hello/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hello</title>
</head>
<body>
    <h1>Hello, world!</h1>
</body>
</html>

practice/newyear/templates/newyear/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Is it new year?</title>
    <link href="{% static 'newyear/styles.css' %}" rel="stylesheet">
</link>
<body>
    {% if newyear %}
        <h1>YES</h1>
    {% else %}
        <h1>NO</h1>
    {% endif %}
</body>
</html>

practice/task/templates/task/add.html
{% extends "task/layout.html" %}

{% block body %}
    <h1>Add Tasks</h1>
    <form action="{% url 'task:add' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="text" name="task">
        <input type="submit">
    </form>
    <a href="{% url 'task:index' %}">View Task</a>
{% endblock %}

practice/task/templates/task/index.html
{% extends "task/layout.html" %}

{% block body %}
    <h1>Task</h1>
    <ul>
        {% for task in task %}
            <li>{{ task }}</li>
        {% endfor %}
    </ul>
    <a href="{% url 'task:add' %}">Add a New Task</a>
{% endblock %}

practice/task/templates/task/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Task</title>
</head>
<body>
    {% block body %}
    {% endblock %}
</body>
</html>